version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: social_db
    restart: unless-stopped
    volumes:
      - social_postgresql_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -p ${POSTGRES_PORT} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: social_backend
    restart: always
    command: >
      bash -c "alembic revision --autogenerate -m "Initial" &&
               alembic upgrade head &&
               uvicorn src.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - cache_pip_volume:/root/.cache/pip/:rw
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis:latest
    container_name: social_redis
    restart: always
    ports:
      - "6379:6379"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: social_celery
    restart: always
    command: bash -c "celery -A src.tasks.tasks:celery worker --loglevel=INFO"
    volumes:
      - cache_pip_volume:/root/.cache/pip/:rw
    env_file:
      - ./.env
    depends_on:
      redis:
        condition: service_healthy

volumes:
  social_postgresql_volume:
  cache_pip_volume:  
